version: "3"
services:

  #
  # Gateway
  #
  gateway:
    hostname: "gateway"
    image: wolfulus/traefik-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  #
  # MySQL
  #
  mysql:
    hostname: "mysql"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "directus"
    restart: always
    ports:
      - "3306:3306"
    logging:
      driver: none

  #
  # Builder
  #
  builder:
    hostname: "builder"
    image: wolfulus/directus-builder:local
    build:
      context: ./builder/
    command: "true"
    tty: true

  #
  # API
  #
  api:
    hostname: "api"
    image: wolfulus/directus-api:local
    build:
      context: ./projects/api/
      args:
        BUILDER_IMAGE: "wolfulus/directus-builder:local"
        API_VERSION: "2.0.2"
    depends_on:
      - builder
    environment:
      DATABASE_HOST: "mysql"
      DATABASE_NAME: "directus2"
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.backend: "api"
      traefik.frontend.rule: "Host:api.localtest.me"
    tty: true

  #
  # App
  #
  app:
    hostname: "app"
    image: wolfulus/directus-app:local
    build:
      context: ./projects/app/
      args:
        BUILDER_IMAGE: "wolfulus/directus-builder:local"
        APP_VERSION: "7.0.2"
    depends_on:
      - builder
    environment:
      API_ENDPOINT: "API; http://api.localtest.me/_/"
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.backend: "app"
      traefik.frontend.rule: "Host:app.localtest.me"
    tty: true
